"""Shared resource limits for authenticated Chromium-backed item search."""

SEARCH_KEYWORD_MAX_CHARS = 120
SEARCH_ACCOUNT_ID_MAX_CHARS = 128
SEARCH_PAGE_MAX = 20
SEARCH_PAGE_SIZE_MAX = 50
SEARCH_TOTAL_PAGES_MAX = 10
SEARCH_GLOBAL_CONCURRENCY = 2
SEARCH_OPERATION_TIMEOUT_SECONDS = 90.0
